### ISSUE TITLE
Question on use-case

### ISSUE THREAD

**Issue by gchp** [reem/rust-void#1]
Sorry to open an issue for this.

I'm just curious, what's the reason I'd want to use `Void` over `()`? Don't they serve the same purpose?
I've seen `Void` used in a few iron examples. I've replaced this in my own code with `()`, so I'm curious as to the reasoning behind its usage.

``` rust
fn sample() -> Result<String, ()>;
// works just as well as
fn sample() -> Result<String, Void>;

impl SomeTrait for MyType {
    type Error = Void;
    // or
    type Error = ();
}
```

Not sure if I'm missing something, or if its just a style choice?

**Comment by reem** [comment]
@gchp Sorry for not getting back to this, for some reason I wasn't watching this repo.

The difference between `()` and `Void` is that there are values of type `()`, whereas it is impossible to construct a value of type `Void` in code that is reachable.

This means that if you _do_ have a value with type `Void` you _must_ be in unreachable code. We liberally hint this to the optimizer, which then helps the standard aggressive dead code elimination optimizations.
