### ISSUE TITLE
Relicense under dual MIT / Apache-2.0

### ISSUE THREAD

**Issue by notriddle** [reem/rust-void#9]
Contributors who'll need to sign off on this:
- [x] @notriddle
- [x] @fitzgen 
- [x] @reem 
- [x] @ipetkov 
- [x] @lfairy

**Comment by lambda-fairy** [comment]
Sounds good to me. :+1:

**Comment by ipetkov** [comment]
Sure :+1:

**Comment by fitzgen** [comment]
Sure

**Comment by notriddle** [comment]
Cool, everybody's signed off on it.

**Comment by posborne** [comment]
👍  from me as well

**Comment by dtolnay** [comment]
Looks like this was done in #8.
